route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - match:
      alertname: InstanceDown
  receiver: 'alert-team'

receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'examplemail.com:465'
        auth_username: 'yourmail@examplemail.com'
        auth_password: "your mail password"
        from: 'yourmail@examplemail.com'
        to: 'someonesmail@examplemail.com'
        require_tls: false # if you have problems with tls